### ISSUE TITLE
Medcoupling version 9.12

### ISSUE THREAD

**Issue by bahugo** [jschueller/medcoupling-wheels#1]
Hello, first of all, thank you for your packaging work, it helps a lot!

I'd like to package 9.12.0 version of medcoupling, i'm wondering if it would be as easy as adding this version to your ci matrix, or if it will be necessary to update your build dependencies too?

If it's easy, i'll open a pull request.

Tkank you

**Comment by jschueller** [comment]
yes, it should just be a matter of updating the versions, feel free to send a PR
