### ISSUE TITLE
Packaging with pyproject.toml

### ISSUE THREAD

**Issue by bahugo** [jschueller/medcoupling-wheels#3]
The generated RECORD file is not complete, which causes installation issues with pixi and uv.

The RECORD file must contain the list of all package files with their hashes and sizes.

A walkaround would be to use a pyproject.toml (PEP518) and python "build" package to build the wheel.
The compilation step would stay outside of the pyproject.toml and all compilation output files could be indexed as package data.

**Comment by jschueller** [comment]
or I have a python script to write it: https://github.com/openturns/build-wheels/blob/master/write_distinfo.py
